name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We're building Kindling to help fiction writers, and your ideas are valuable.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a frustration?
      placeholder: As a writer, I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of Kindling does this relate to?
      options:
        - Import (Plottr, Scrivener, Markdown)
        - Outline View
        - Writing/Prose Editor
        - Beat Sheet
        - Characters & Locations
        - Export
        - UI/UX
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to your workflow?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Critical - I can't use Kindling without it

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I would be willing to help implement this feature
          required: false
