#!/usr/bin/env node
/**
 * Build qa/visual/results/index.md: one row per checkpoint, one column per
 * run, from the verdict tables in each run's report.md.
 *
 *   node qa/visual/history.mjs
 *
 * A verdict cell is reduced to a symbol: pass ✓, regression ✗, inconclusive ?,
 * not run / not covered –. The run header carries the cost line from the
 * report (tool calls, screenshots, wall clock) when present.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "results");
const runs = readdirSync(root, { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(join(root, d.name, "report.md")))
  .map((d) => d.name)
  .sort();

const symbol = (verdict) => {
  const v = verdict.toLowerCase();
  if (/regression|fail/.test(v)) return "✗";
  if (/inconclusive/.test(v)) return "?";
  if (/not run|not covered|not repeated|not captured/.test(v)) return "–";
  if (/pass/.test(v)) return "✓";
  return "·";
};

const checkpoints = new Map(); // id -> { label, [run]: symbol }
const costs = {};
for (const run of runs) {
  const md = readFileSync(join(root, run, "report.md"), "utf8");
  const cost = md.match(/^- Cost: (.+)$/m);
  costs[run] = cost ? cost[1].replace(/\s+/g, " ").trim() : "";
  for (const line of md.split("\n")) {
    const m = line.match(/^\|\s*(\d\d-\d\d[^|]*?)\s*\|\s*([^|]+?)\s*\|/);
    if (!m) continue;
    const id = m[1].split(/[\s,]/)[0];
    const entry = checkpoints.get(id) || { label: m[1] };
    entry[run] = symbol(m[2]);
    checkpoints.set(id, entry);
  }
}

const ids = [...checkpoints.keys()].sort();
const header = `| Checkpoint | ${runs.join(" | ")} |`;
const sep = `| --- | ${runs.map(() => "---").join(" | ")} |`;
const rows = ids.map((id) => {
  const e = checkpoints.get(id);
  return `| ${id} ${e.label.replace(id, "").trim()} | ${runs.map((r) => e[r] || " ").join(" | ")} |`;
});
const costRows = runs.map((r) => `- ${r}: ${costs[r] || "no cost line"}`);

const out = [
  "# Visual QA run history",
  "",
  "Generated by `node qa/visual/history.mjs`. ✓ pass, ✗ regression, ? inconclusive, – not run.",
  "",
  "## Cost per run",
  "",
  ...costRows,
  "",
  "## Verdicts",
  "",
  header,
  sep,
  ...rows,
  "",
].join("\n");

writeFileSync(join(root, "index.md"), out);
console.log(`index.md: ${ids.length} checkpoints across ${runs.length} runs`);
